console.log("saloni ojha");
console.error("0 division error");
console.warn("error may occure");
console.info;

let student={name:"saloni",age:20,course:"cse"};
console.table(student);
console.table(["apple","b","c"]);
console.time("test");
for(let i=0;i<10000;i++){}
    console.timeEnd("test");

console.group("cse24");
console.log("name:saloni");
console.groupEnd()  ;
console.count("click");
console.count("click");
console.count("click");
console.count("click");
console.count("click");
console.dir(document.body);    //  IT IS USED TO SHOW THE PROPERTIES OF THE JAVASCRIPT

